apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensearch-file-api.fullname" . }}-opensearch
  labels:
    {{- include "opensearch-file-api.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.config.opensearch.password | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensearch-file-api.fullname" . }}-jwt
  labels:
    {{- include "opensearch-file-api.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.config.jwt.secret | b64enc | quote }}

{{- if eq .Values.config.storage.type "s3" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensearch-file-api.fullname" . }}-s3
  labels:
    {{- include "opensearch-file-api.labels" . | nindent 4 }}
type: Opaque
data:
  keyId: {{ .Values.config.storage.s3KeyId | b64enc | quote }}
  secret: {{ .Values.config.storage.s3Secret | b64enc | quote }}
{{- end }}
